# Generated by Django 5.2.8 on 2025-12-13 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0014_tbl_assignsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=50)),
                ('student_contact', models.CharField(max_length=50)),
                ('student_address', models.CharField(max_length=50)),
                ('student_photo', models.FileField(upload_to='Assets/StudentDocs/')),
                ('student_gender', models.CharField(max_length=50)),
                ('student_dob', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
                ('assignclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_assignclass')),
            ],
        ),
    ]
