# Generated by Django 5.2.8 on 2025-12-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_assignsubject'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_file', models.FileField(upload_to='Assets/Notes/')),
                ('notes_content', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teacher')),
            ],
        ),
    ]
