# Generated by Django 5.2.8 on 2026-01-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_tbl_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignment',
        ),
    ]
