# Generated by Django 5.2.8 on 2026-01-02 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_assignsubject'),
        ('Teacher', '0006_delete_tbl_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=100)),
                ('assignment_file', models.FileField(upload_to='Assets/Assignments/')),
                ('assignment_duedate', models.DateField()),
                ('assignment_date', models.DateField(auto_now_add=True)),
                ('as_status', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teacher')),
            ],
        ),
    ]
