# Generated by Django 5.2.8 on 2026-01-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0011_tbl_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student',
            name='student_registernumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
