# Generated by Django 5.2.11 on 2026-03-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_tbl_notification_tbl_specialtimetable'),
        ('Teacher', '0012_tbl_student_student_registernumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_teacherleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_title', models.CharField(max_length=200)),
                ('leave_reason', models.TextField()),
                ('leave_status', models.IntegerField(default=0)),
                ('leave_date', models.DateField(auto_now_add=True)),
                ('leave_fromdate', models.DateField(null=True)),
                ('leave_todate', models.DateField(null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teacher')),
            ],
        ),
    ]
