# Generated by Django 5.2.8 on 2025-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_academicyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyear_name', models.CharField(max_length=50)),
            ],
        ),
    ]
