# Generated by Django 5.2.8 on 2025-12-12 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=60)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_course')),
            ],
        ),
    ]
