# Generated by Django 5.2.8 on 2025-12-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_email', models.CharField(max_length=50)),
                ('teacher_contact', models.CharField(max_length=50)),
                ('teacher_role', models.CharField(max_length=50)),
                ('teacher_gender', models.CharField(max_length=50)),
                ('teacher_photo', models.FileField(upload_to='Assets/TeacherDocs/')),
                ('teacher_password', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department')),
            ],
        ),
    ]
