# Generated by Django 5.2.8 on 2025-12-13 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_assignclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_academicyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teacher')),
            ],
        ),
    ]
