# Generated by Django 5.2.8 on 2026-01-16 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_assignsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_classsem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_assignclass')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_semester')),
            ],
        ),
    ]
