# Generated by Django 5.2.8 on 2026-01-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_timetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_timetable',
            old_name='staff',
            new_name='teacher_id',
        ),
    ]
