# Generated by Django 5.2.8 on 2026-01-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_rename_staff_tbl_timetable_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(max_length=100)),
            ],
        ),
    ]
