# Generated by Django 5.2.8 on 2026-01-31 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_tbl_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_incharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_purpose')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_teacher')),
            ],
        ),
    ]
