# Generated by Django 5.2.12 on 2026-03-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_tbl_notification_tbl_specialtimetable'),
        ('Guest', '0002_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_time', models.DateTimeField(auto_now_add=True)),
                ('otp_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
