# Generated by Django 5.2.8 on 2026-01-02 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0002_tbl_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_title', models.CharField(max_length=200)),
                ('com_content', models.TextField()),
                ('com_date', models.DateField(auto_now_add=True)),
                ('com_status', models.IntegerField(default=0)),
                ('com_reply', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_student')),
            ],
        ),
    ]
