# Generated by Django 5.2.8 on 2026-01-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
        ('Teacher', '0009_tbl_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignmentbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_date', models.DateField(auto_now_add=True)),
                ('ass_status', models.IntegerField(default=0)),
                ('ass_score', models.CharField(max_length=200)),
                ('ass_file', models.FileField(upload_to='', verbose_name='Assets/Files/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_student')),
            ],
        ),
    ]
