# Generated by Django 5.2.8 on 2026-01-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_tbl_assignmentbody'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignmentbody',
        ),
    ]
