# Generated by Django 5.2.8 on 2026-01-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_tbl_assignmentbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_assignmentbody',
            name='ass_file',
            field=models.FileField(upload_to='Assets/Assignment/Files/'),
        ),
    ]
