# Generated by Django 5.2.8 on 2026-01-31 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_tbl_assignmentbody_ass_file'),
        ('Teacher', '0011_tbl_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_title', models.CharField(max_length=200)),
                ('leave_reason', models.TextField()),
                ('leave_status', models.IntegerField(default=0)),
                ('leave_fromdate', models.DateField()),
                ('leave_todate', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_student')),
            ],
        ),
    ]
