# Generated by Django 5.2.8 on 2026-01-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_tbl_leave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_leave',
        ),
    ]
