# Generated by Django 5.2.8 on 2026-01-31 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_tbl_incharge'),
        ('Student', '0008_tbl_leave'),
        ('Teacher', '0011_tbl_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='dutyleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dutyleave_date', models.DateField(auto_now_add=True)),
                ('dutyleave_status', models.IntegerField(default=0)),
                ('dutyleave_reason', models.TextField()),
                ('dutyleave_hour', models.CharField(max_length=100)),
                ('dutyleave_fromdate', models.DateField(null=True)),
                ('dutyleave_todate', models.DateField(null=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_purpose')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_student')),
            ],
        ),
    ]
