# Generated by Django 5.2.8 on 2026-01-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_dutyleave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dutyleave',
        ),
    ]
